export enum Categories {
  Basic = 'Basic',
  Bitwise = 'Bitwise',
  ComplexNumbers = 'Complex numbers',
  Graphing = 'Graphing',
  Interpolation = 'Interpolation',
  Distributions = 'Distributions',
  Statistics = 'Statistics',
  Calculus = 'Calculus',
  Polynomials = 'Polynomials',
  Solving = 'Solving',
  Trigonometric = 'Trigonometric',
  Hyperbolic = 'Hyperbolic',
  LogAndExponential = 'Log and exponential',
  SpecialFunctions = 'Special functions',
  LinearAlgebra = 'Linear algebra',
}
